# permissions for end users to view hubpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubpool-viewer-role
rules:
- apiGroups:
  - openshift.io.openshift.io
  resources:
  - hubpools
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - openshift.io.openshift.io
  resources:
  - hubpools/status
  verbs:
  - get
