# permissions for end users to edit hubpools.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hubpool-editor-role
rules:
- apiGroups:
  - openshift.io.openshift.io
  resources:
  - hubpools
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - openshift.io.openshift.io
  resources:
  - hubpools/status
  verbs:
  - get
